# Laboratorio 4, Parte 2 — Análisis de modelos usando datos geoespaciales

**Universidad del Valle de Guatemala**
Facultad de Ingeniería — Departamento de Ciencias de la Computación
CC3084 – Data Science, Semestre II 2026

Integrantes: Diego López, Nelson Escalante, Roberto Nájera

Este notebook ejecuta el avance de los ejercicios 1, 2 y 3 (preparación del
dataset, variable respuesta, y selección de predictores) importando
directamente las funciones ya implementadas y probadas en `src/tabular.py`,
`src/response_variable.py` y `src/predictors.py`. No reimplementa ninguna
lógica aquí: este notebook es la vitrina narrativa de un proceso cuyo código
fuente vive versionado en `src/`.

In [1]:
import sys
from pathlib import Path

# permite importar config y src.* al correr el notebook desde notebooks/
sys.path.insert(0, str(Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()))

import config
config.ensure_output_dirs()

## 1. Preparación de los datos para Machine Learning

**Autor: Persona 1 (Parte 2) — `src/tabular.py`**

Se construye, a partir de los raster de la Parte I, un conjunto de datos
tabular donde cada fila es una observación geográfica válida dentro de
alguno de los lagos.

In [2]:
from src.tabular import generate_tabular_dataset, print_dataset_summary, save_dataset_summary_csv

# generate_tabular_dataset() descarga las bandas si no existen (skip_existing=True
# por defecto, no vuelve a descargar lo ya presente en data/rasters/) y guarda
# un CSV por lago/fecha en data/tabular/. Puede tardar si faltan bandas.
df_tabular = generate_tabular_dataset()
df_tabular.head()

============================================================
TABULAR: ATITLAN
============================================================

[process] atitlan 2025-01-18
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-01-18\bands.tif

[ok] 474,797 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-01-18.csv
[ok] atitlan 2025-01-18: 474,797 observaciones validas

[process] atitlan 2025-04-13
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-04-13\bands.tif

[ok] 1,024,554 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-04-13.csv
[ok] atitlan 2025-04-13: 1,024,554 observaciones validas

[process] atitlan 2025-05-13
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-05-13\bands.tif

[ok] 920,906 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-05-13.csv
[ok] atitlan 2025-05-13: 920,906 observaciones validas

[process] atitlan 2025-07-17
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-07-17\bands.tif

[ok] 815,154 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-07-17.csv
[ok] atitlan 2025-07-17: 815,154 observaciones validas

[process] atitlan 2025-11-21
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-11-21\bands.tif

[ok] 612,507 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-11-21.csv
[ok] atitlan 2025-11-21: 612,507 observaciones validas

[process] atitlan 2025-12-29
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2025-12-29\bands.tif

[ok] 715,298 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2025-12-29.csv
[ok] atitlan 2025-12-29: 715,298 observaciones validas

[process] atitlan 2026-02-12
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2026-02-12\bands.tif

[ok] 820,569 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2026-02-12.csv
[ok] atitlan 2026-02-12: 820,569 observaciones validas

[process] atitlan 2026-03-24
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2026-03-24\bands.tif

[ok] 983,657 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2026-03-24.csv
[ok] atitlan 2026-03-24: 983,657 observaciones validas

[process] atitlan 2026-04-13
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2026-04-13\bands.tif

[ok] 1,002,876 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2026-04-13.csv
[ok] atitlan 2026-04-13: 1,002,876 observaciones validas

[process] atitlan 2026-04-28
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2026-04-28\bands.tif

[ok] 1,013,435 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2026-04-28.csv
[ok] atitlan 2026-04-28: 1,013,435 observaciones validas

[process] atitlan 2026-07-22
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\atitlan\2026-07-22\bands.tif

[ok] 852,947 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\atitlan\2026-07-22.csv
[ok] atitlan 2026-07-22: 852,947 observaciones validas

============================================================
TABULAR: AMATITLAN
============================================================

[process] amatitlan 2025-01-28
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2025-01-28\bands.tif

[ok] 145,784 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2025-01-28.csv
[ok] amatitlan 2025-01-28: 145,784 observaciones validas

[process] amatitlan 2025-04-15
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2025-04-15\bands.tif

[ok] 144,434 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2025-04-15.csv
[ok] amatitlan 2025-04-15: 144,434 observaciones validas

[process] amatitlan 2025-04-28
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2025-04-28\bands.tif

[ok] 144,407 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2025-04-28.csv
[ok] amatitlan 2025-04-28: 144,407 observaciones validas

[process] amatitlan 2025-11-24
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2025-11-24\bands.tif

[ok] 145,639 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2025-11-24.csv
[ok] amatitlan 2025-11-24: 145,639 observaciones validas

[process] amatitlan 2026-01-08
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-01-08\bands.tif

[ok] 145,531 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-01-08.csv
[ok] amatitlan 2026-01-08: 145,531 observaciones validas

[process] amatitlan 2026-02-02
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-02-02\bands.tif

[ok] 139,008 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-02-02.csv
[ok] amatitlan 2026-02-02: 139,008 observaciones validas

[process] amatitlan 2026-02-07
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-02-07\bands.tif

[ok] 145,615 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-02-07.csv
[ok] amatitlan 2026-02-07: 145,615 observaciones validas

[process] amatitlan 2026-03-29
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-03-29\bands.tif

[ok] 146,022 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-03-29.csv
[ok] amatitlan 2026-03-29: 146,022 observaciones validas

[process] amatitlan 2026-04-13
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-04-13\bands.tif

[ok] 146,629 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-04-13.csv
[ok] amatitlan 2026-04-13: 146,629 observaciones validas

[process] amatitlan 2026-04-28
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-04-28\bands.tif

[ok] 137,106 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-04-28.csv
[ok] amatitlan 2026-04-28: 137,106 observaciones validas

[process] amatitlan 2026-06-19
[skip] ya existe C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\rasters\amatitlan\2026-06-19\bands.tif

[ok] 146,110 filas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\data\tabular\amatitlan\2026-06-19.csv
[ok] amatitlan 2026-06-19: 146,110 observaciones validas

,lake,date,longitude,latitude,b2,b3,b4,b8,ndvi,ndwi,cyano
0,atitlan,2025-01-18,-91.168568,14.748007,0.0239,0.0294,0.0229,0.0253,0.049793,0.074954,4.315603
1,atitlan,2025-01-18,-91.168466,14.748007,0.0258,0.0339,0.0271,0.0296,0.044092,0.067717,4.679797
2,atitlan,2025-01-18,-91.168364,14.748007,0.0324,0.0412,0.0364,0.0421,0.072611,-0.010804,3.379761
3,atitlan,2025-01-18,-91.169689,14.747813,0.0107,0.0120,0.0025,0.0078,0.514563,0.212121,3.680668
4,atitlan,2025-01-18,-91.168976,14.747813,0.0104,0.0088,0.0013,0.0043,0.535714,0.343511,3.211020

### 1.1 - 1.3: construcción, columnas mínimas y limpieza

El dataset resultante tiene una fila por píxel válido dentro del contorno
real de cada lago (GeoJSON), ya excluyendo nubes/sombras/nieve (filtro SCL),
píxeles sin dato válido de Sentinel-2 (`dataMask`), y observaciones donde
NDVI/NDWI no pudieron calcularse por denominador cero.

In [3]:
print("columnas:", list(df_tabular.columns))
print("filas:", f"{len(df_tabular):,}")

columnas: ['lake', 'date', 'longitude', 'latitude', 'b2', 'b3', 'b4', 'b8', 'ndvi', 'ndwi', 'cyano']
filas: 10,822,985

### 1.4: total de observaciones, por lago, por fecha, variables, tipos y % de faltantes

Persistido en `outputs/tables/dataset_summary.csv`,
`dataset_summary_by_lake.csv` y `dataset_summary_by_date.csv`.

In [4]:
print_dataset_summary(df_tabular)
save_dataset_summary_csv(df_tabular)

============================================================
RESUMEN DEL DATASET
============================================================

Total de observaciones: 10,822,985

Observaciones por lago:

lake
amatitlan    1586285
atitlan      9236700
dtype: int64

Observaciones por lago y fecha:

lake       date
amatitlan  2025-01-28     145784
           2025-04-15     144434
           2025-04-28     144407
           2025-11-24     145639
           2026-01-08     145531
           2026-02-02     139008
           2026-02-07     145615
           2026-03-29     146022
           2026-04-13     146629
           2026-04-28     137106
           2026-06-19     146110
atitlan    2025-01-18     474797
           2025-04-13    1024554
           2025-05-13     920906
           2025-07-17     815154
           2025-11-21     612507
           2025-12-29     715298
           2026-02-12     820569
           2026-03-24     983657
           2026-04-13    1002876
           2026-04-28    1013435
           2026-07-22     852947
dtype: int64

Variables disponibles:
- lake
- date
- longitude
- latitude
- b2
- b3
- b4
- b8
- ndvi
- ndwi
- cyano

Tipos de variables:
lake          object
date          object
longitude    float64
latitude     float64
b2           float32
b3           float32
b4           float32
b8           float32
ndvi         float32
ndwi         float32
cyano        float32
dtype: object

Porcentaje de valores faltantes:

lake         0.0
date         0.0
longitude    0.0
latitude     0.0
b2           0.0
b3           0.0
b4           0.0
b8           0.0
ndvi         0.0
ndwi         0.0
cyano        0.0
dtype: float64

[ok] resumen de variables guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\dataset_summary.csv

[ok] total y observaciones por lago guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\dataset_summary_by_lake.csv

[ok] observaciones por lago y fecha guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\dataset_summary_by_date.csv

(WindowsPath('C:/Users/djlop/OneDrive/DIEGO/UVG/2026/segundo semestre/DATA SCIENCE/Lab-4/outputs/tables/dataset_summary.csv'),
 WindowsPath('C:/Users/djlop/OneDrive/DIEGO/UVG/2026/segundo semestre/DATA SCIENCE/Lab-4/outputs/tables/dataset_summary_by_lake.csv'),
 WindowsPath('C:/Users/djlop/OneDrive/DIEGO/UVG/2026/segundo semestre/DATA SCIENCE/Lab-4/outputs/tables/dataset_summary_by_date.csv'))

### 1.5 - 1.6: análisis exploratorio y decisiones de preparación

El EDA completo de las variables candidatas (estadísticas descriptivas,
distribución por clase, boxplots y matriz de correlación) se hace en la
sección 3 de este notebook, una vez que la variable respuesta `high_cyano`
ya está construida — ver `src/predictors.py`.

## 2. Construcción de la variable respuesta

**Autor: Persona 2 (Parte 2) — `src/response_variable.py`**

Se construye `high_cyano` (0/1) a partir del índice de cianobacteria, con un
punto de corte justificado en bibliografía científica (OMS 2021), y se
analiza su distribución y balance de clases.

In [5]:
from src.response_variable import run_response_variable_analysis

response_results = run_response_variable_analysis(df_tabular)
df_final = response_results["df"]  # dataset con high_cyano ya agregado
df_final.head()

[ok] resumen de distribución de la respuesta guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\response_variable_summary.csv
[ok] distribución por fecha guardada en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\response_by_date.csv

[ok] gráfica de balance de clases guardada en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\response_balance.png
[ok] gráfica de evolución de la respuesta guardada en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\response_evolution_by_date.png

## Ejercicio 2: variable respuesta (high_cyano)

**Punto de corte**: 12 µg/L de clorofila-a (1 = alta presencia, cyano > 12; 0 = ausente/baja). World Health Organization (2021). Guidelines on Recreational Water Quality: Volume 1 - Coastal and Fresh Waters. Geneva: WHO (actualiza WHO 2003/2009). Niveles de clorofila-a con dominancia de cianobacterias: Vigilancia 1-12 µg/L, Alerta 1 12-24 µg/L, Alerta 2 >24 µg/L. Ver también Chorus & Testai (eds.), Toxic Cyanobacteria in Water, 2021, cap. 5; y CyanoLakes (Kravitz & Matthews, 2020), autores del script de cianobacteria adaptado en este proyecto (src/indices.py), que aplica estos mismos cortes.

### 2.3 Distribución de la respuesta

- Globalmente: 98.7% de las observaciones caen en clase 0 (baja/ausente) y 1.3% en clase 1 (alta presencia). Ver `response_balance.png` (por lago) y `response_evolution_by_date.png` (evolución por fecha) para el detalle.

### 2.4 Balance de clases

- La clase minoritaria es 1 con 1.3% de las observaciones (razón mayoría:minoría ≈ 78.37:1). Clasificación: **desbalance severo**.
- Consecuencias esperadas: un modelo entrenado sin corrección puede sesgarse hacia la clase mayoritaria y lograr un accuracy alto simplemente prediciendo la clase dominante, sin detectar bien los casos de alta presencia de cianobacteria (que son justamente los que importan desde el punto de vista de salud pública). Accuracy por sí sola sería una métrica engañosa; conviene priorizar recall/F1/ROC-AUC de la clase 1, y considerar balanceo (class_weight, sobremuestreo/submuestreo, o umbrales de decisión ajustados) al entrenar los modelos en el ejercicio 4.

### 2.5 Variables excluidas por data leakage

**Prohibidas (excluir siempre de X):**
- `cyano`: high_cyano se construye directamente como cyano > umbral. Es una transformación 1 a 1 de la respuesta -- incluirla como predictor sería leakage total y garantizaría una separación perfecta artificial.

**Uso con precaución (coordinar con Persona 3):**
- `b4`: B04 es uno de los dos insumos directos del NDCI que produce el valor numérico de cyano (chl = f((B05-B04)/(B05+B04))). El otro insumo, B05, no está en el dataset tabular, así que b4 por sí solo NO determina cyano -- pero sí participa matemáticamente en su cálculo. Se recomienda evaluarlo con cautela (por ejemplo comparando desempeño del modelo con y sin b4) antes de darlo por seguro como predictor. También participa en la máscara de agua (water body classifier) que decide qué píxeles se incluyen en el dataset, junto con b2, b3 y b8.

**Seguras como predictoras (no participan en el cálculo de cyano):**
- `b2`: No participa en el NDCI de cianobacteria; solo interviene (junto con b3,b4,b8) en la máscara de agua que decide inclusión/exclusión de píxeles, no en el valor numérico de cyano.
- `b3`: No participa en el NDCI de cianobacteria. Se usa para NDWI y en la máscara de agua.
- `b8`: No participa en el NDCI de cianobacteria (usa B04 y B05, no B08). Se usa para NDVI/NDWI y en la máscara de agua.
- `ndvi`: Calculado a partir de b4 y b8; no involucra B05, así que no reproduce el NDCI de cyano.
- `ndwi`: Calculado a partir de b3 y b8; no interviene en el cálculo de cyano.
- `longitude`: Coordenada geográfica, no interviene en el cálculo espectral de cyano.
- `latitude`: Coordenada geográfica, no interviene en el cálculo espectral de cyano.

,lake,date,longitude,latitude,b2,b3,b4,b8,ndvi,ndwi,cyano,high_cyano
0,atitlan,2025-01-18,-91.168568,14.748007,0.0239,0.0294,0.0229,0.0253,0.049793,0.074954,4.315603,0
1,atitlan,2025-01-18,-91.168466,14.748007,0.0258,0.0339,0.0271,0.0296,0.044092,0.067717,4.679797,0
2,atitlan,2025-01-18,-91.168364,14.748007,0.0324,0.0412,0.0364,0.0421,0.072611,-0.010804,3.379761,0
3,atitlan,2025-01-18,-91.169689,14.747813,0.0107,0.0120,0.0025,0.0078,0.514563,0.212121,3.680668,0
4,atitlan,2025-01-18,-91.168976,14.747813,0.0104,0.0088,0.0013,0.0043,0.535714,0.343511,3.211020,0

### 2.2: justificación del punto de corte

Ver `src/response_variable.py::THRESHOLD_SOURCE` para la referencia
bibliográfica completa (OMS 2021; Chorus & Testai 2021; CyanoLakes/Kravitz &
Matthews 2020, mismos autores del script de cianobacteria de este proyecto).

In [6]:
from src.response_variable import HIGH_CYANO_THRESHOLD_UGL, THRESHOLD_SOURCE

print(f"Umbral: cyano > {HIGH_CYANO_THRESHOLD_UGL:.0f} µg/L de clorofila-a")
print()
print(THRESHOLD_SOURCE)

Umbral: cyano > 12 µg/L de clorofila-a

World Health Organization (2021). Guidelines on Recreational Water Quality: Volume 1 - Coastal and Fresh Waters. Geneva: WHO (actualiza WHO 2003/2009). Niveles de clorofila-a con dominancia de cianobacterias: Vigilancia 1-12 µg/L, Alerta 1 12-24 µg/L, Alerta 2 >24 µg/L. Ver también Chorus & Testai (eds.), Toxic Cyanobacteria in Water, 2021, cap. 5; y CyanoLakes (Kravitz & Matthews, 2020), autores del script de cianobacteria adaptado en este proyecto (src/indices.py), que aplica estos mismos cortes.

### 2.3 - 2.4: distribución de la respuesta y balance de clases

Resultados guardados en `outputs/tables/response_variable_summary.csv` y
`response_by_date.csv`; gráficas en `outputs/figures/response_balance.png`
y `response_evolution_by_date.png`.

In [7]:
print(response_results["interpretation"])

## Ejercicio 2: variable respuesta (high_cyano)

**Punto de corte**: 12 µg/L de clorofila-a (1 = alta presencia, cyano > 12; 0 = ausente/baja). World Health Organization (2021). Guidelines on Recreational Water Quality: Volume 1 - Coastal and Fresh Waters. Geneva: WHO (actualiza WHO 2003/2009). Niveles de clorofila-a con dominancia de cianobacterias: Vigilancia 1-12 µg/L, Alerta 1 12-24 µg/L, Alerta 2 >24 µg/L. Ver también Chorus & Testai (eds.), Toxic Cyanobacteria in Water, 2021, cap. 5; y CyanoLakes (Kravitz & Matthews, 2020), autores del script de cianobacteria adaptado en este proyecto (src/indices.py), que aplica estos mismos cortes.

### 2.3 Distribución de la respuesta

- Globalmente: 98.7% de las observaciones caen en clase 0 (baja/ausente) y 1.3% en clase 1 (alta presencia). Ver `response_balance.png` (por lago) y `response_evolution_by_date.png` (evolución por fecha) para el detalle.

### 2.4 Balance de clases

- La clase minoritaria es 1 con 1.3% de las observaciones (razón mayoría:minoría ≈ 78.37:1). Clasificación: **desbalance severo**.
- Consecuencias esperadas: un modelo entrenado sin corrección puede sesgarse hacia la clase mayoritaria y lograr un accuracy alto simplemente prediciendo la clase dominante, sin detectar bien los casos de alta presencia de cianobacteria (que son justamente los que importan desde el punto de vista de salud pública). Accuracy por sí sola sería una métrica engañosa; conviene priorizar recall/F1/ROC-AUC de la clase 1, y considerar balanceo (class_weight, sobremuestreo/submuestreo, o umbrales de decisión ajustados) al entrenar los modelos en el ejercicio 4.

### 2.5 Variables excluidas por data leakage

**Prohibidas (excluir siempre de X):**
- `cyano`: high_cyano se construye directamente como cyano > umbral. Es una transformación 1 a 1 de la respuesta -- incluirla como predictor sería leakage total y garantizaría una separación perfecta artificial.

**Uso con precaución (coordinar con Persona 3):**
- `b4`: B04 es uno de los dos insumos directos del NDCI que produce el valor numérico de cyano (chl = f((B05-B04)/(B05+B04))). El otro insumo, B05, no está en el dataset tabular, así que b4 por sí solo NO determina cyano -- pero sí participa matemáticamente en su cálculo. Se recomienda evaluarlo con cautela (por ejemplo comparando desempeño del modelo con y sin b4) antes de darlo por seguro como predictor. También participa en la máscara de agua (water body classifier) que decide qué píxeles se incluyen en el dataset, junto con b2, b3 y b8.

**Seguras como predictoras (no participan en el cálculo de cyano):**
- `b2`: No participa en el NDCI de cianobacteria; solo interviene (junto con b3,b4,b8) en la máscara de agua que decide inclusión/exclusión de píxeles, no en el valor numérico de cyano.
- `b3`: No participa en el NDCI de cianobacteria. Se usa para NDWI y en la máscara de agua.
- `b8`: No participa en el NDCI de cianobacteria (usa B04 y B05, no B08). Se usa para NDVI/NDWI y en la máscara de agua.
- `ndvi`: Calculado a partir de b4 y b8; no involucra B05, así que no reproduce el NDCI de cyano.
- `ndwi`: Calculado a partir de b3 y b8; no interviene en el cálculo de cyano.
- `longitude`: Coordenada geográfica, no interviene en el cálculo espectral de cyano.
- `latitude`: Coordenada geográfica, no interviene en el cálculo espectral de cyano.

### 2.5: variables excluidas por data leakage

Ver la sección "Variables excluidas por data leakage" impresa arriba —
`cyano` queda prohibida (transformación 1 a 1 de la respuesta) y `b4` se
marca con cautela (participa matemáticamente en el índice de cianobacteria).

## 3. Selección y construcción de variables predictoras

**Autor: Persona 3 (Parte 2) — `src/predictors.py`**

Se caracterizan las variables candidatas (EDA), se aplica el control de
leakage ya definido en la sección 2, y se define la lista formal y
justificada de predictores.

In [8]:
from src.predictors import run_predictor_analysis

predictor_results = run_predictor_analysis(df_final)

[ok] estadisticas descriptivas guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\predictors_descriptive_stats.csv

[ok] estadisticas por clase guardadas en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\predictors_stats_by_class.csv

[ok] boxplot de b2 guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_b2.png

[ok] boxplot de b3 guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_b3.png

[ok] boxplot de b4 guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_b4.png

[ok] boxplot de b8 guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_b8.png

[ok] boxplot de ndvi guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_ndvi.png

[ok] boxplot de ndwi guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_ndwi.png

[ok] boxplot de cyano guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_cyano.png

[ok] boxplot de longitude guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_longitude.png

[ok] boxplot de latitude guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\boxplot_latitude.png

[ok] heatmap de correlación guardado en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\figures\predictors\correlation_heatmap.png

## Preparación y limpieza del dataset (aplicada aguas arriba)

Persona 1 (src/tabular.py::raster_to_dataframe) ya aplicó, antes de que este dataset llegara a Persona 3, las siguientes reglas de limpieza -- no se repiten ni se reimplementan aquí:
- Máscara del contorno real del lago (GeoJSON), excluyendo tierra fuera del lago.
- Exclusión de píxeles con clases problemáticas de la Scene Classification Layer (SCL): NoData, saturados/defectuosos, sombra de nube, nube media/alta probabilidad, cirros delgados y nieve/hielo.
- Exclusión de píxeles con dataMask=0 (sin dato válido de Sentinel-2).
- Eliminación de observaciones donde NDVI o NDWI no pudieron calcularse por denominador cero.

Esto ya se refleja en el 0% de valores faltantes observado en las estadísticas descriptivas de este módulo: no significa que no hiciera falta limpieza, sino que esa limpieza ya se hizo antes de generar los CSV.
[ok] lista definitiva de predictores guardada en C:\Users\djlop\OneDrive\DIEGO\UVG\2026\segundo semestre\DATA SCIENCE\Lab-4\outputs\tables\final_predictors.csv

## Selección de predictores (incisos 3.1-3.3)

Recordatorio (definido por Persona 2, no redefinido aquí): high_cyano = 1 cuando cyano > 12 µg/L de clorofila-a; 0 en caso contrario.

### Exclusiones por data leakage (definidas por Persona 2, aplicadas aquí)

- `cyano` (prohibida): high_cyano se construye directamente como cyano > umbral. Es una transformación 1 a 1 de la respuesta -- incluirla como predictor sería leakage total y garantizaría una separación perfecta artificial.
- `b4` (excluida por precaución): B04 es uno de los dos insumos directos del NDCI que produce el valor numérico de cyano (chl = f((B05-B04)/(B05+B04))). El otro insumo, B05, no está en el dataset tabular, así que b4 por sí solo NO determina cyano -- pero sí participa matemáticamente en su cálculo. Se recomienda evaluarlo con cautela (por ejemplo comparando desempeño del modelo con y sin b4) antes de darlo por seguro como predictor. También participa en la máscara de agua (water body classifier) que decide qué píxeles se incluyen en el dataset, junto con b2, b3 y b8.

### Catálogo de predictores candidatos retenidos

- `b2` (banda_espectral): Reflectancia en la banda azul (B02) de Sentinel-2. Interviene junto con b3, b4 y b8 en el clasificador de cuerpo de agua que usa el propio script de cianobacteria del proyecto; ayuda a distinguir agua de otras superficies, relevante como contexto espectral.
- `b3` (banda_espectral): Reflectancia en la banda verde (B03) de Sentinel-2. Es uno de los dos insumos de NDWI y participa en la máscara de agua; el verde es sensible a pigmentos fotosintéticos suspendidos en el agua, lo que la vincula plausiblemente con biomasa algal.
- `b8` (banda_espectral): Reflectancia en el infrarrojo cercano (B08) de Sentinel-2. Insumo de NDVI y NDWI, y parte de la máscara de agua; el infrarrojo cercano distingue fuertemente agua de vegetación/tierra, útil como contexto para interpretar el resto de índices.
- `ndvi` (indice_espectral): Índice de vegetación normalizado, calculado a partir de b4 y b8. Puede detectar materia vegetal/orgánica visible en superficie (ej. acumulaciones de algas o plantas acuáticas flotantes), un contexto plausible para floraciones algales.
- `ndwi` (indice_espectral): Índice de agua normalizado, calculado a partir de b3 y b8. Distingue agua clara de zonas con más turbidez o materia en suspensión; un NDWI más bajo dentro del cuerpo de agua puede coincidir con zonas de mayor concentración de partículas, incluida biomasa de cianobacteria.
- `longitude` (caracteristica_espacial): Coordenada geográfica (longitud) del centro del píxel. No interviene en el cálculo espectral de cyano (segura contra leakage), pero es una característica de ubicación, no espectral: no generaliza entre lagos ni necesariamente a fechas futuras -- riesgo de que el modelo memorice ubicaciones específicas en vez de aprender un patrón espectral transferible. Se incluye como candidata con esta limitación documentada explícitamente.
- `latitude` (caracteristica_espacial): Coordenada geográfica (latitud) del centro del píxel. Misma consideración que longitude: segura contra leakage, pero con el mismo riesgo de sobreajuste geográfico en vez de señal espectral generalizable.

### Pares altamente correlacionados (observado en los datos)

- `longitude` y `latitude`: r = -0.949

### Exclusiones por redundancia (decisión de diseño)

- Ninguna: no hubo pares con |r| >= 0.95, así que no se forzó ninguna reducción adicional de la lista de candidatas retenidas.

### Lista definitiva de predictores

`b2`, `b3`, `b8`, `ndvi`, `ndwi`, `longitude`, `latitude`

### 3.1 - 3.2: catálogo de predictores retenidos, con justificación individual

In [9]:
for entry in predictor_results["predictor_catalog"]:
    print(f"- {entry['name']} ({entry['type']}): {entry['description']}")
    print(f"  {entry['rationale']}\n")

- b2 (banda_espectral): Reflectancia en la banda azul (B02) de Sentinel-2.
  Interviene junto con b3, b4 y b8 en el clasificador de cuerpo de agua que usa el propio script de cianobacteria del proyecto; ayuda a distinguir agua de otras superficies, relevante como contexto espectral.

- b3 (banda_espectral): Reflectancia en la banda verde (B03) de Sentinel-2.
  Es uno de los dos insumos de NDWI y participa en la máscara de agua; el verde es sensible a pigmentos fotosintéticos suspendidos en el agua, lo que la vincula plausiblemente con biomasa algal.

- b8 (banda_espectral): Reflectancia en el infrarrojo cercano (B08) de Sentinel-2.
  Insumo de NDVI y NDWI, y parte de la máscara de agua; el infrarrojo cercano distingue fuertemente agua de vegetación/tierra, útil como contexto para interpretar el resto de índices.

- ndvi (indice_espectral): Índice de vegetación normalizado, calculado a partir de b4 y b8.
  Puede detectar materia vegetal/orgánica visible en superficie (ej. acumulaciones de algas o plantas acuáticas flotantes), un contexto plausible para floraciones algales.

- ndwi (indice_espectral): Índice de agua normalizado, calculado a partir de b3 y b8.
  Distingue agua clara de zonas con más turbidez o materia en suspensión; un NDWI más bajo dentro del cuerpo de agua puede coincidir con zonas de mayor concentración de partículas, incluida biomasa de cianobacteria.

- longitude (caracteristica_espacial): Coordenada geográfica (longitud) del centro del píxel.
  No interviene en el cálculo espectral de cyano (segura contra leakage), pero es una característica de ubicación, no espectral: no generaliza entre lagos ni necesariamente a fechas futuras -- riesgo de que el modelo memorice ubicaciones específicas en vez de aprender un patrón espectral transferible. Se incluye como candidata con esta limitación documentada explícitamente.

- latitude (caracteristica_espacial): Coordenada geográfica (latitud) del centro del píxel.
  Misma consideración que longitude: segura contra leakage, pero con el mismo riesgo de sobreajuste geográfico en vez de señal espectral generalizable.

### 3.3: ingeniería de características

No se construyó ninguna variable derivada nueva en este avance: la matriz de
correlación (`outputs/figures/predictors/correlation_heatmap.png`) no mostró
ninguna redundancia por encima del umbral de exclusión (|r| ≥ 0.95, ver
`REDUNDANCY_THRESHOLD` en `src/predictors.py`) que amerite una
transformación adicional — decisión documentada, no una omisión.

### Lista definitiva de predictores

In [10]:
print(", ".join(predictor_results["final_predictors"]))

b2, b3, b8, ndvi, ndwi, longitude, latitude